version: 2.1

jobs:
  semgrep-scan:
    parameters: 

    environment:
      # Scan changed files in PRs, block on new issues only (existing issues ignored)
      # SEMGREP_BASELINE_REF: << parameters.diff_branch >>
      SEMGREP_REPO_URL: << pipeline.project.git_url >>
      SEMGREP_BRANCH: << pipeline.git.branch >>

      # Change job timeout (default is 1800 seconds; set to 0 to disable)
      # SEMGREP_TIMEOUT: 300

    docker:
      - image: returntocorp/semgrep
    steps:
      - checkout
      - run:
          name: "Semgrep scan"
          command: semgrep ci
workflows:
  Semgrep:
    jobs:
      - semgrep-scan
